CREATE GLOBAL TEMPORARY TABLE SYSMATRICULAS.REPORTEMATRICULADOS(
    ID NUMBER,
    NOMBRE VARCHAR2(50),
    EMAIL VARCHAR (50),
    TELEFONO VARCHAR2(50),
    CURSO VARCHAR2(50),
    DOCENTE VARCHAR2(50),
    LOCAL VARCHAR2(50),
    COD_ MATRICULA VARCHAR2(50), 
    ESTADO_PAGO VARCHAR2(50) 
)ON COMMIT PRESERVE ROWS; 

CREATE OR REPLACE PROCEDURE SYSMATRICULAS.SP_GENERAREPORTEMATRICULADOS
IS
V_ESTADO VARCHAR(10);
BEGIN

  DELETE FROM SYSMATRICULAS.REPORTEMATRICULADOS;
  COMMIT;

INSERT INTO SYSMATRICULAS.REPORTEMATRICULADOS ( ID, NOMBRE, EMAIL, TELEFONO, CURSO,
    DOCENTE, LOCAL,  COD_ MATRICULA, ESTADO_PAGO)
SELECT A.ALUMNOCODIGO, A.ALUMNONOMBRE, A.ALUMNOEMAIL,A.ALUMNOTELEFONO, 
C.CURSONOMBRE, D.DOCENTENOMBRE, L.LOCALNOMBRE, M.MATRICULACODIGO, P.PAGOESTADO	
FROM SYSMATRICULAS.ALUMNO A
INNER JOIN SYSMATRICULAS.MATRICULA M ON M.ALUMNOCODIGO = A.ALUMNOCODIGO
INNER JOIN SYSMATRICULAS.CURSO C ON C.CURSOCODIGO = M.CURSOCODIGO
INNER JOIN SYSMATRICULAS.DOCENTE D ON D.DOCENTECODIGO = M.DOCENTECODIGO
INNER JOIN SYSMATRICULAS.LOCAL L ON L.LOCALCODIGO = M.LOCALCODIGO
INNER JOIN SYSMATRICULAS.PAGO P ON P.MATRICULACODIGO = M.MATRICULACODIGO
;

UPDATE SYSMATRICULAS.REPORTEMATRICULADOS SET
ESTADO_PAGO='CANCELADO'
WHERE 
ESTADO_PAGO='1';

END;
/

CALL SYSMATRICULAS.SP_GENERAREPORTEMATRICULADOS();

SELECT * FROM SYSMATRICULAS.REPORTEMATRICULADOS
