CREATE GLOBAL TEMPORARY TABLE SYSMATRICULAS.REPORTECURSOS(
   ID  NUMBER,
   CURSO VARCHAR2(50),
   ID_DOC NUMBER,
   DOCENTE VARCHAR2(50),
   MATRICULADOS VARCHAR2(2),
   DISPONIBLE VARCHAR2 (2),
   PRECIO NUMBER,
   PROYECTADO VARCHAR2(50),
   COMPROMETIDO  VARCHAR2(50),
   RECAUDADO VARCHAR2(50)
)ON COMMIT PRESERVE ROWS; 

CREATE OR REPLACE PROCEDURE SYSMATRICULAS.SP_GENERAREPORTECURSOS
IS
  V_COMPROMETIDO    NUMBER(10);
  V_RECAUDADO    NUMBER(10);
BEGIN
 
  DELETE FROM SYSMATRICULAS.REPORTECURSOS;
  COMMIT;


INSERT INTO SYSMATRICULAS.REPORTECURSOS(ID,CURSO, ID_DOC, DOCENTE , MATRICULADOS,DISPONIBLE,PRECIO, PROYECTADO, COMPROMETIDO,RECAUDADO)
SELECT 
C.CURSOCODIGO, C.CURSONOMBRE, D.DOCENTECODIGO, D.DOCENTENOMBRE, COUNT(M.MATRICULACODIGO) AS MATRICULADOS, (CD.CURSODOCENTECANTIDAD - COUNT(M.MATRICULACODIGO)) AS VACANTES , CD.CURSODOCENTECOSTO,(CD.CURSODOCENTECANTIDAD * CD.CURSODOCENTECOSTO) AS PROYECTADO ,0,0
FROM SYSMATRICULAS.CURSO_DOCENTE CD
LEFT JOIN SYSMATRICULAS.CURSO C ON C.CURSOCODIGO=CD.CURSOCODIGO
LEFT JOIN SYSMATRICULAS.DOCENTE D ON D.DOCENTECODIGO=CD.DOCENTECODIGO
LEFT JOIN SYSMATRICULAS.MATRICULA M ON M.CURSOCODIGO=CD.CURSOCODIGO AND M.DOCENTECODIGO=CD.DOCENTECODIGO
GROUP BY C.CURSOCODIGO, D.DOCENTECODIGO,C.CURSONOMBRE, D.DOCENTENOMBRE,CD.CURSODOCENTECOSTO,CD.CURSODOCENTECANTIDAD
ORDER BY C.CURSONOMBRE;

FOR R IN (select ID, ID_DOC from SYSMATRICULAS.REPORTECURSOS) loop
    
   SELECT NVL(SUM(CD.CURSODOCENTECOSTO),0) INTO V_COMPROMETIDO
    from SYSMATRICULAS.CURSO_DOCENTE CD 
    INNER JOIN SYSMATRICULAS.MATRICULA M ON M.CURSOCODIGO=CD.CURSOCODIGO AND M.DOCENTECODIGO=CD.DOCENTECODIGO
    WHERE NOT EXISTS(
    SELECT P.MATRICULACODIGO FROM SYSMATRICULAS.PAGO P WHERE  P.MATRICULACODIGO=M.MATRICULACODIGO)
    AND  CD.CURSOCODIGO=R.ID
    AND  CD.DOCENTECODIGO =R.ID_DOC;
    
   
    SELECT NVL(SUM(P.PAGOMONTO),0) INTO V_RECAUDADO
    from SYSMATRICULAS.PAGO P
    INNER JOIN SYSMATRICULAS.MATRICULA M ON P.MATRICULACODIGO=M.MATRICULACODIGO
    INNER JOIN SYSMATRICULAS.CURSO_DOCENTE CD ON M.CURSOCODIGO=CD.CURSOCODIGO AND M.DOCENTECODIGO=CD.DOCENTECODIGO
    where CD.CURSOCODIGO= R.ID
    AND CD.DOCENTECODIGO= R.ID_DOC;
    
       
    -- Actualizar tabla RESUMEN
    update SYSMATRICULAS.REPORTECURSOS
    set COMPROMETIDO = COMPROMETIDO,
        RECAUDADO    = V_RECAUDADO
    where ID = R.ID
    AND ID_DOC = R.ID_DOC;  
  end loop;
  
  END;
/


call SYSMATRICULAS.SP_GENERAREPORTECURSOS();

SELECT * FROM SYSMATRICULAS.REPORTECURSOS;