
CREATE OR REPLACE PACKAGE SCOTT.PKG_DEMO AS

FUNCTION FN_SUMAR( P_N1 IN NUMBER, P_N2 IN NUMBER )
RETURN NUMBER;

FUNCTION FN_SUMAR( P_N1 IN NUMBER, P_N2 IN NUMBER, P_N3 IN NUMBER )
RETURN NUMBER;

END;
/


CREATE OR REPLACE PACKAGE BODY SCOTT.PKG_DEMO AS

FUNCTION FN_SUMAR( P_N1 IN NUMBER, P_N2 IN NUMBER )
RETURN NUMBER
IS
BEGIN
  RETURN (P_N1 + P_N2);
END;


FUNCTION FN_SUMAR( P_N1 IN NUMBER, P_N2 IN NUMBER, P_N3 IN NUMBER )
RETURN NUMBER
IS
BEGIN
  RETURN (P_N1 + P_N2 + P_N3);
END;

END;
/


SELECT SCOTT.pkg_demo.fn_sumar(65,34) FROM DUAL;

SELECT SCOTT.pkg_demo.fn_sumar(65,34,65) FROM DUAL;




