CREATE OR REPLACE PROCEDURE LOGISTICA.SP_TIENDA_ALERTA(
p_cursor out nocopy SYS_REFCURSOR )
IS
BEGIN

DELETE FROM LOGISTICA.ALERTA_TIENDA;
  COMMIT;
  
  INSERT INTO LOGISTICA.ALERTA_TIENDA(TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, PRODES, TOTAL )
  select TIENOM, TIEADMPAT AS PATERNO ,TIEADMMAT AS MATERNO, TIEADMNOM AS NOMBRES, PRODES, SUM(DETPEDCAN) AS TOTAL
    from tienda A
    INNER JOIN PEDIDO B ON A.ID_TIENDA = B.ID_TIENDA
    inner join detalle_pedido C on B.ID_PEDIDO=C.ID_PEDIDO AND  B.ID_TIENDA = C.ID_TIENDA 
    inner join producto D on c.id_producto= D.id_producto
    WHERE A.ID_TIENDA <> c.id_tienda_atiende
    GROUP BY TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, PRODES;

COMMIT;
    
  -- REPORTE
  open p_cursor for
  select TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, PRODES, TOTAL 
  from LOGISTICA.ALERTA_TIENDA;

  END;
  /