SET DEFINE OFF;
Insert into LOGISTICA.TIENDA
   (ID_TIENDA, TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, TIEDIR, TIEFECINI)
 Values
   (1, 'TECNOLOGIA DE PUNTA', 'DIAZ', 'RAMOS', 'CARLOS', 'Los rosales 731 ', TO_DATE('01/30/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into LOGISTICA.TIENDA
   (ID_TIENDA, TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, TIEDIR, TIEFECINI)
 Values
   (2, 'MEDIATIENDA', 'PRADO', 'GARCIA', 'CESAR', 'praderas bajas 1478', TO_DATE('02/25/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into LOGISTICA.TIENDA
   (ID_TIENDA, TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, TIEDIR, TIEFECINI)
 Values
   (3, 'LA CASA ELECTRONICA', 'BRAVO', 'VERA', 'JUAN', 'villarica 985', TO_DATE('05/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into LOGISTICA.TIENDA
   (ID_TIENDA, TIENOM, TIEADMPAT, TIEADMMAT, TIEADMNOM, TIEDIR, TIEFECINI)
 Values
   (4, 'TU LUGAR', 'CASAS', 'LOPEZ', 'HERNAN', 'olaya 1896', TO_DATE('06/10/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
