SET DEFINE OFF;
Insert into LOGISTICA.PRODUCTO
   (ID_PRODUCTO, PRODES, PROUNIMED, PROPRE, PROCAT)
 Values
   (1, 'LAPTOP', '0001', 5000, '0001');
Insert into LOGISTICA.PRODUCTO
   (ID_PRODUCTO, PRODES, PROUNIMED, PROPRE, PROCAT)
 Values
   (2, 'ONLYONE', '0001', 2000, '0001');
Insert into LOGISTICA.PRODUCTO
   (ID_PRODUCTO, PRODES, PROUNIMED, PROPRE, PROCAT)
 Values
   (3, 'DISCO DURO', '0001', 600, '0001');
Insert into LOGISTICA.PRODUCTO
   (ID_PRODUCTO, PRODES, PROUNIMED, PROPRE, PROCAT)
 Values
   (4, 'TELEVISOR', '0001', 4000, '0002');
COMMIT;
