CREATE USER LOGISTICA IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE TO LOGISTICA;
ALTER USER LOGISTICA
QUOTA UNLIMITED ON USERS;
GRANT CREATE VIEW TO LOGISTICA;

CREATE TABLE LOGISTICA.DETALLE_PEDIDO
(
    ID_DETPEDIDO         NUMBER NOT NULL ,
    ID_PEDIDO            NUMBER NOT NULL ,
    ID_TIENDA            NUMBER NOT NULL ,
    ID_PRODUCTO          NUMBER NULL ,
    ID_TIENDA_ATIENDE    NUMBER NULL ,
    DETPEDCAN            NUMBER NULL 
);



CREATE UNIQUE INDEX XPKDETALLE_PEDIDO ON LOGISTICA.DETALLE_PEDIDO
(ID_DETPEDIDO   ASC,ID_PEDIDO   ASC,ID_TIENDA   ASC);



ALTER TABLE LOGISTICA.DETALLE_PEDIDO
    ADD CONSTRAINT  XPKDETALLE_PEDIDO PRIMARY KEY (ID_DETPEDIDO,ID_PEDIDO,ID_TIENDA);



CREATE TABLE LOGISTICA.PEDIDO
(
    ID_PEDIDO            NUMBER NOT NULL ,
    ID_TIENDA            NUMBER NOT NULL ,
    PEDFEC               DATE NULL ,
    PEDTIP               VARCHAR2(3) NULL 
);



CREATE UNIQUE INDEX XPKPEDIDO ON LOGISTICA.PEDIDO
(ID_PEDIDO   ASC,ID_TIENDA   ASC);



ALTER TABLE LOGISTICA.PEDIDO
    ADD CONSTRAINT  XPKPEDIDO PRIMARY KEY (ID_PEDIDO,ID_TIENDA);



CREATE TABLE LOGISTICA.PRODUCTO
(
    ID_PRODUCTO          NUMBER NOT NULL ,
    PRODES               VARCHAR2(150) NULL ,
    PROUNIMED            VARCHAR2(4) NULL ,
    PROPRE               NUMBER(15,2) NULL ,
    PROCAT               VARCHAR2(4) NULL 
);



CREATE UNIQUE INDEX XPKPRODUCTO ON LOGISTICA.PRODUCTO
(ID_PRODUCTO   ASC);



ALTER TABLE LOGISTICA.PRODUCTO
    ADD CONSTRAINT  XPKPRODUCTO PRIMARY KEY (ID_PRODUCTO);



CREATE TABLE LOGISTICA.STOCK_TIENDA
(
    ID_TIENDA            NUMBER NOT NULL ,
    ID_PRODUCTO          NUMBER NOT NULL ,
    STOCKCANT            NUMBER NULL 
);



CREATE UNIQUE INDEX XPKSTOCK_TIENDA ON LOGISTICA.STOCK_TIENDA
(ID_TIENDA   ASC,ID_PRODUCTO   ASC);



ALTER TABLE LOGISTICA.STOCK_TIENDA
    ADD CONSTRAINT  XPKSTOCK_TIENDA PRIMARY KEY (ID_TIENDA,ID_PRODUCTO);



CREATE TABLE LOGISTICA.TIENDA
(
    ID_TIENDA            NUMBER NOT NULL ,
    TIENOM               VARCHAR2(150) NULL ,
    TIEADMPAT            VARCHAR2(150) NULL ,
    TIEADMMAT            VARCHAR2(150) NULL ,
    TIEADMNOM            VARCHAR2(150) NULL ,
    TIEDIR               VARCHAR2(200) NULL ,
    TIEFECINI            DATE NULL 
);



CREATE UNIQUE INDEX XPKTIENDA ON LOGISTICA.TIENDA
(ID_TIENDA   ASC);



ALTER TABLE LOGISTICA.TIENDA
    ADD CONSTRAINT  XPKTIENDA PRIMARY KEY (ID_TIENDA);



ALTER TABLE LOGISTICA.DETALLE_PEDIDO
    ADD (CONSTRAINT R_4 FOREIGN KEY (ID_PEDIDO, ID_TIENDA) REFERENCES LOGISTICA.PEDIDO (ID_PEDIDO, ID_TIENDA));



ALTER TABLE LOGISTICA.DETALLE_PEDIDO
    ADD (CONSTRAINT R_5 FOREIGN KEY (ID_PRODUCTO) REFERENCES LOGISTICA.PRODUCTO (ID_PRODUCTO) ON DELETE SET NULL);



ALTER TABLE LOGISTICA.PEDIDO
    ADD (CONSTRAINT R_3 FOREIGN KEY (ID_TIENDA) REFERENCES LOGISTICA.TIENDA (ID_TIENDA));



ALTER TABLE LOGISTICA.STOCK_TIENDA
    ADD (CONSTRAINT R_1 FOREIGN KEY (ID_TIENDA) REFERENCES LOGISTICA.TIENDA (ID_TIENDA));



ALTER TABLE LOGISTICA.STOCK_TIENDA
    ADD (CONSTRAINT R_2 FOREIGN KEY (ID_PRODUCTO) REFERENCES LOGISTICA.PRODUCTO (ID_PRODUCTO));

CREATE SEQUENCE LOGISTICA.TIENDA_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE LOGISTICA.PEDIDO_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE LOGISTICA.DETPEDIDO_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE GLOBAL TEMPORARY TABLE LOGISTICA.ALERTA_TIENDA(
  TIENOM       VARCHAR2(100),
  TIEADMPAT    VARCHAR2(100),
  TIEADMMAT    VARCHAR2(100),
  TIEADMNOM    VARCHAR2(100),
  PRODES       VARCHAR2(100),
  TOTAL  NUMBER
) ON COMMIT PRESERVE ROWS;
