CREATE OR REPLACE PACKAGE LOGISTICA.PKG_CRUD_TIENDA AS
  
  PROCEDURE SP_INS_TIENDA(
    P_TIENOM       IN LOGISTICA.TIENDA.TIENOM%TYPE,
    P_TIEADMPAT    IN LOGISTICA.TIENDA.TIEADMPAT%TYPE,
    P_TIEADMMAT           IN LOGISTICA.TIENDA.TIEADMMAT%TYPE,
    P_TIEADMNOM           IN LOGISTICA.TIENDA.TIEADMNOM%TYPE,
    P_TIEDIR           IN LOGISTICA.TIENDA.TIEDIR%TYPE
  );

  PROCEDURE SP_UPD_TIENDA(
    P_ID_TIENDA        IN LOGISTICA.TIENDA.ID_TIENDA%TYPE,
    P_TIENOM       IN LOGISTICA.TIENDA.TIENOM%TYPE,
    P_TIEADMPAT    IN LOGISTICA.TIENDA.TIEADMPAT%TYPE,
    P_TIEADMMAT           IN LOGISTICA.TIENDA.TIEADMMAT%TYPE,
    P_TIEADMNOM           IN LOGISTICA.TIENDA.TIEADMNOM%TYPE,
    P_TIEDIR           IN LOGISTICA.TIENDA.TIEDIR%TYPE
  );

  PROCEDURE SP_DEL_TIENDA(
    P_ID_TIENDA        IN LOGISTICA.TIENDA.ID_TIENDA%TYPE
  );

  PROCEDURE SP_LISTAR_TIENDA(
    P_CURSOR OUT NOCOPY SYS_REFCURSOR
  );

END PKG_CRUD_TIENDA;
/

